"""
Django settings for sanders_dashboard_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os # Pastikan ini diimpor!
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tl0n5z+hi9(#b+wwsk-dvf=aahot(v)e47d8*5(3qw^c(o1psc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Untuk development, ini aman. Untuk production, daftar hostname spesifik.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',          # Sistem autentikasi Django
    'django.contrib.contenttypes',
    'django.contrib.sessions',      # Untuk manajemen sesi
    'django.contrib.messages',      # Untuk pesan (misalnya "Anda berhasil login")
    'django.contrib.staticfiles',
    'core_dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sanders_dashboard_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Gunakan os.path.join untuk memastikan kompatibilitas path di berbagai OS
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True, # Ini penting agar Django juga mencari template di folder 'templates' di setiap aplikasi
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Tambahkan kembali ini
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sanders_dashboard_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# staging local

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_staging',
        'USER': 'go_user',
        'PASSWORD': 'Sanders123!',
        'HOST': '127.0.0.1',
        'PORT': '3306', # Sebaiknya cantumkan port 3306 secara eksplisit jika itu default Anda
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Sesuaikan zona waktu dengan lokasi Anda jika ingin log atau waktu yang ditampilkan sesuai
TIME_ZONE = 'Asia/Jakarta' # Mengacu pada Bandung, West Java, Indonesia

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Direktori tempat Django akan mencari file statis Anda (selain dari folder 'static' di dalam apps)
# Pastikan folder 'static' ada di root proyek Anda (sejajar dengan manage.py)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Gunakan os.path.join
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication URLs
LOGIN_REDIRECT_URL = '/'      # URL untuk redirect setelah login sukses
LOGOUT_REDIRECT_URL = '/login/' # URL untuk redirect setelah logout sukses
LOGIN_URL = '/login/'         # URL untuk halaman login Anda